# Generated by Django 5.2.7 on 2025-11-04 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('prompt_type', models.CharField(choices=[('usp_extraction', 'USP Extraction'), ('keyword_generation', 'Keyword Generation'), ('ad_copy_generation', 'Ad Copy Generation'), ('campaign_analysis', 'Campaign Analysis'), ('service_identification', 'Service Identification')], max_length=30)),
                ('template', models.TextField()),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIAnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('input_data', models.JSONField()),
                ('results', models.JSONField(blank=True, null=True)),
                ('tokens_used', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.client')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignOptimizationSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optimization_type', models.CharField(choices=[('budget_allocation', 'Budget Allocation'), ('keyword_expansion', 'Keyword Expansion'), ('ad_group_split', 'Ad Group Split'), ('negative_keywords', 'Negative Keywords'), ('bid_adjustment', 'Bid Adjustment')], max_length=30)),
                ('suggestion', models.TextField()),
                ('expected_impact', models.TextField()),
                ('confidence_score', models.FloatField()),
                ('is_implemented', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_integration.aianalysissession')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedAdCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline_1', models.CharField(max_length=30)),
                ('headline_2', models.CharField(max_length=30)),
                ('headline_3', models.CharField(blank=True, max_length=30)),
                ('description_1', models.CharField(max_length=90)),
                ('description_2', models.CharField(blank=True, max_length=90)),
                ('quality_score', models.FloatField(default=0.5)),
                ('relevance_score', models.FloatField(default=0.5)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.adgroup')),
                ('ai_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_integration.aianalysissession')),
            ],
        ),
        migrations.CreateModel(
            name='KeywordSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_text', models.CharField(max_length=200)),
                ('suggested_match_type', models.CharField(max_length=10)),
                ('search_volume_estimate', models.IntegerField(blank=True, null=True)),
                ('competition_estimate', models.CharField(blank=True, max_length=20)),
                ('relevance_score', models.FloatField()),
                ('suggested_cpc', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('ai_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_integration.aianalysissession')),
            ],
        ),
    ]
