# Generated by Django 5.2.7 on 2026-01-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiprompttemplate',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='aiprompttemplate',
            name='model_settings',
            field=models.JSONField(blank=True, default=dict, help_text="AI model settings: {'model': 'gpt-4.1', 'temperature': 0.7, 'max_tokens': 500}"),
        ),
        migrations.AddField(
            model_name='aiprompttemplate',
            name='placeholders',
            field=models.JSONField(blank=True, default=list, help_text="List of placeholder definitions: [{'name': '{service_name}', 'description': 'Servicens navn'}]"),
        ),
        migrations.AddField(
            model_name='aiprompttemplate',
            name='prompt_text',
            field=models.TextField(blank=True, help_text='The actual prompt template with placeholders'),
        ),
        migrations.AddField(
            model_name='aiprompttemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='aiprompttemplate',
            name='prompt_type',
            field=models.CharField(choices=[('usp_extraction', 'USP Extraction'), ('keyword_generation', 'Keyword Generation'), ('ad_copy_generation', 'Ad Copy Generation'), ('campaign_analysis', 'Campaign Analysis'), ('service_identification', 'Service Identification'), ('generate_descriptions', 'Google Ads Beskrivelser'), ('generate_meta_tags', 'Meta Tags (Programmatic)'), ('generate_seo_meta_tags', 'SEO Meta Tags')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='aiprompttemplate',
            name='template',
            field=models.TextField(help_text='Legacy field - use prompt_text instead'),
        ),
    ]
