# Generated by Django 5.2.7 on 2025-11-04 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('pages_crawled', models.IntegerField(default=0)),
                ('total_pages', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.client')),
            ],
        ),
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField()),
                ('meta_description', models.TextField(blank=True)),
                ('h1_tags', models.TextField(blank=True)),
                ('h2_tags', models.TextField(blank=True)),
                ('word_count', models.IntegerField(default=0)),
                ('is_service_page', models.BooleanField(default=False)),
                ('is_about_page', models.BooleanField(default=False)),
                ('is_contact_page', models.BooleanField(default=False)),
                ('crawled_at', models.DateTimeField(auto_now_add=True)),
                ('crawl_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.crawlsession')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('service_description', models.TextField(blank=True)),
                ('keywords_found', models.TextField()),
                ('priority_score', models.FloatField(default=0.5)),
                ('web_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.webpage')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedUSP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('context', models.TextField(help_text='Tekst omkring USP for kontekst')),
                ('confidence_score', models.FloatField()),
                ('extraction_method', models.CharField(help_text='AI, Pattern matching, etc.', max_length=50)),
                ('position_on_page', models.CharField(help_text='Header, Hero, Footer, etc.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('web_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.webpage')),
            ],
            options={
                'verbose_name_plural': 'Extracted USPs',
            },
        ),
    ]
