# Generated by Django 5.2.7 on 2025-11-04 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('default_cpc', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_conversion_rate', models.FloatField(blank=True, null=True)),
                ('priority_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('campaign_type', models.CharField(choices=[('search', 'Search'), ('display', 'Display'), ('shopping', 'Shopping'), ('video', 'Video')], max_length=20)),
                ('budget_daily', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_location', models.CharField(max_length=200)),
                ('target_language', models.CharField(default='da', max_length=50)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline_1', models.CharField(max_length=30)),
                ('headline_2', models.CharField(max_length=30)),
                ('headline_3', models.CharField(blank=True, max_length=30)),
                ('description_1', models.CharField(max_length=90)),
                ('description_2', models.CharField(blank=True, max_length=90)),
                ('final_url', models.URLField()),
                ('display_path_1', models.CharField(blank=True, max_length=15)),
                ('display_path_2', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.adgroup')),
            ],
        ),
        migrations.AddField(
            model_name='adgroup',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign'),
        ),
        migrations.CreateModel(
            name='CampaignPerformancePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_ctr', models.FloatField(blank=True, null=True)),
                ('estimated_conversion_rate', models.FloatField(blank=True, null=True)),
                ('estimated_cpc', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_cost_per_conversion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website_url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.industry')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.client'),
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('match_type', models.CharField(choices=[('exact', 'Exact'), ('phrase', 'Phrase'), ('broad', 'Broad')], max_length=10)),
                ('max_cpc', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_search_volume', models.IntegerField(blank=True, null=True)),
                ('competition_level', models.CharField(blank=True, max_length=20, null=True)),
                ('ad_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.adgroup')),
            ],
        ),
    ]
