# Generated by Django 5.2.7 on 2025-11-05 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryPerformancePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=100)),
                ('pattern_type', models.CharField(max_length=50)),
                ('pattern_data', models.JSONField()),
                ('avg_cost_per_conversion', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('avg_conversion_rate', models.FloatField(null=True)),
                ('avg_ctr', models.FloatField(null=True)),
                ('sample_size', models.IntegerField(default=0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('industry_name', 'pattern_type')},
            },
        ),
        migrations.CreateModel(
            name='PerformanceDataImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('campaign', 'Campaign Performance'), ('keyword', 'Keyword Performance'), ('ad', 'Ad Performance')], max_length=20)),
                ('file_name', models.CharField(max_length=200)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('rows_imported', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('error_details', models.TextField(blank=True)),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalKeywordPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('match_type', models.CharField(max_length=10)),
                ('campaign_name', models.CharField(max_length=200)),
                ('ad_group_name', models.CharField(max_length=200)),
                ('client_name', models.CharField(max_length=200)),
                ('industry_category', models.CharField(blank=True, max_length=100)),
                ('conversions', models.IntegerField(default=0)),
                ('cost_per_conversion', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('clicks', models.IntegerField(default=0)),
                ('impressions', models.IntegerField(default=0)),
                ('ctr', models.FloatField(default=0.0)),
                ('avg_cpc', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('keyword_intent', models.CharField(blank=True, max_length=50)),
                ('is_recommended', models.BooleanField(default=False)),
                ('performance_score', models.FloatField(default=0.0)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.performancedataimport')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCampaignPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=200)),
                ('client_name', models.CharField(max_length=200)),
                ('industry_category', models.CharField(blank=True, max_length=100)),
                ('conversions', models.IntegerField(default=0)),
                ('cost_per_conversion', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('clicks', models.IntegerField(default=0)),
                ('impressions', models.IntegerField(default=0)),
                ('ctr', models.FloatField(default=0.0)),
                ('avg_cpc', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_high_performer', models.BooleanField(default=False)),
                ('performance_score', models.FloatField(default=0.0)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.performancedataimport')),
            ],
            options={
                'unique_together': {('campaign_name', 'client_name', 'period_start', 'period_end')},
            },
        ),
    ]
