# Generated by Django 5.2.7 on 2025-11-05 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_industryperformancepattern_performancedataimport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedAdGroupStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_group_name', models.CharField(max_length=200)),
                ('default_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('keywords_count', models.IntegerField(default=0)),
                ('ads_count', models.IntegerField(default=0)),
                ('keyword_theme', models.CharField(blank=True, max_length=200)),
                ('service_category', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='performancedataimport',
            name='import_type',
            field=models.CharField(choices=[('campaign', 'Campaign Performance'), ('keyword', 'Keyword Performance'), ('ad', 'Ad Performance'), ('account_structure', 'Full Account Structure')], max_length=20),
        ),
        migrations.CreateModel(
            name='CampaignArchitecturePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=100)),
                ('pattern_name', models.CharField(max_length=100)),
                ('typical_campaign_structure', models.JSONField()),
                ('keyword_organization_patterns', models.JSONField()),
                ('ad_copy_patterns', models.JSONField()),
                ('negative_keyword_strategy', models.JSONField()),
                ('bidding_patterns', models.JSONField()),
                ('based_on_campaigns', models.IntegerField(default=0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('success_indicators', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('industry_name', 'pattern_name')},
            },
        ),
        migrations.CreateModel(
            name='ImportedAdStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline_1', models.CharField(blank=True, max_length=100)),
                ('headline_2', models.CharField(blank=True, max_length=100)),
                ('headline_3', models.CharField(blank=True, max_length=100)),
                ('description_1', models.CharField(blank=True, max_length=200)),
                ('description_2', models.CharField(blank=True, max_length=200)),
                ('final_url', models.URLField(blank=True)),
                ('display_path_1', models.CharField(blank=True, max_length=50)),
                ('display_path_2', models.CharField(blank=True, max_length=50)),
                ('ad_format_pattern', models.CharField(blank=True, max_length=100)),
                ('usp_elements', models.TextField(blank=True)),
                ('ad_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_ads', to='campaigns.importedadgroupstructure')),
            ],
        ),
        migrations.CreateModel(
            name='ImportedCampaignStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=200)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('industry_category', models.CharField(blank=True, max_length=100)),
                ('campaign_type', models.CharField(blank=True, max_length=50)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_type', models.CharField(blank=True, max_length=50)),
                ('bidding_strategy', models.CharField(blank=True, max_length=100)),
                ('target_cpa', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('locations', models.TextField(blank=True)),
                ('languages', models.CharField(blank=True, max_length=100)),
                ('ad_groups_count', models.IntegerField(default=0)),
                ('keywords_count', models.IntegerField(default=0)),
                ('ads_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.performancedataimport')),
            ],
        ),
        migrations.AddField(
            model_name='importedadgroupstructure',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_ad_groups', to='campaigns.importedcampaignstructure'),
        ),
        migrations.CreateModel(
            name='ImportedKeywordStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_text', models.CharField(max_length=200)),
                ('match_type', models.CharField(max_length=20)),
                ('max_cpc', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('final_url', models.URLField(blank=True)),
                ('keyword_intent', models.CharField(blank=True, max_length=50)),
                ('keyword_category', models.CharField(blank=True, max_length=100)),
                ('ad_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_keywords', to='campaigns.importedadgroupstructure')),
            ],
        ),
        migrations.CreateModel(
            name='ImportedNegativeKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_text', models.CharField(max_length=200)),
                ('match_type', models.CharField(max_length=20)),
                ('level', models.CharField(choices=[('campaign', 'Campaign Level'), ('ad_group', 'Ad Group Level')], max_length=20)),
                ('negative_category', models.CharField(blank=True, max_length=100)),
                ('ad_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.importedadgroupstructure')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.importedcampaignstructure')),
            ],
        ),
    ]
