# Generated by Django 5.2.7 on 2025-11-12 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_importedadgroupstructure_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template navn, f.eks. 'Murer Standard'", max_length=100)),
                ('service_name', models.CharField(help_text="Service navn, f.eks. 'Murer', 'VVS'", max_length=50)),
                ('meta_title_template', models.CharField(default='{SERVICE} {BYNAVN} - 5/5 Stjerner på Trustpilot - Ring idag', help_text='Brug {SERVICE}, {BYNAVN}, {URL_SLUG} placeholders', max_length=200)),
                ('meta_description_template', models.TextField(default='Skal du bruge en dygtig {SERVICE} i {BYNAVN}, vi har hjælpet mere end 500 kunder. Kontakt os idag, vi køre dagligt i {BYNAVN}', help_text='Brug {SERVICE}, {BYNAVN}, {URL_SLUG} placeholders')),
                ('headline_1_template', models.CharField(default='{SERVICE} {BYNAVN}', max_length=30)),
                ('headline_2_template', models.CharField(default='5/5 Stjerner Trustpilot', max_length=30)),
                ('description_1_template', models.CharField(default='Professionel {SERVICE} i {BYNAVN} - Ring i dag!', max_length=90)),
                ('page_content_template', models.TextField(blank=True, help_text='WordPress side indhold template med placeholders')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Geo Template',
                'verbose_name_plural': 'Geo Templates',
            },
        ),
        migrations.CreateModel(
            name='GeoExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('google_ads', 'Google Ads Import'), ('wordpress', 'WordPress WP All Import'), ('combined', 'Combined Export')], max_length=20)),
                ('cities_exported', models.JSONField(help_text='Liste over eksporterede byer')),
                ('keywords_count', models.IntegerField(default=0)),
                ('google_ads_file_path', models.CharField(blank=True, max_length=500)),
                ('wordpress_file_path', models.CharField(blank=True, max_length=500)),
                ('exported_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                ('exported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.geotemplate')),
            ],
        ),
        migrations.CreateModel(
            name='GeoKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('city_slug', models.CharField(max_length=100)),
                ('keyword_text', models.CharField(max_length=200)),
                ('match_type', models.CharField(choices=[('exact', 'Exact'), ('phrase', 'Phrase'), ('broad', 'Broad')], default='phrase', max_length=10)),
                ('max_cpc', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('final_url', models.URLField(help_text='Landing page URL, f.eks. /murer-bagsvaerd/')),
                ('meta_title', models.CharField(max_length=200)),
                ('meta_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_keywords', to='campaigns.campaign')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.geotemplate')),
            ],
            options={
                'unique_together': {('campaign', 'keyword_text')},
            },
        ),
    ]
