# Generated by Django 5.2.7 on 2025-11-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_geotemplate_geoexport_geokeyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='ad_rotation',
            field=models.CharField(choices=[('optimize', 'Optimize'), ('rotate_evenly', 'Rotate evenly'), ('rotate_indefinitely', 'Rotate indefinitely')], default='optimize', max_length=30),
        ),
        migrations.AddField(
            model_name='campaign',
            name='bidding_strategy',
            field=models.CharField(choices=[('manual_cpc', 'Manual CPC'), ('enhanced_cpc', 'Enhanced CPC'), ('target_cpa', 'Target CPA'), ('maximize_clicks', 'Maximize clicks'), ('target_roas', 'Target ROAS')], default='enhanced_cpc', max_length=30),
        ),
        migrations.AddField(
            model_name='campaign',
            name='budget_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('total', 'Total Campaign')], default='daily', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='default_bid',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Default CPC for ad groups', max_digits=8),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_cpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target CPA (if using Target CPA bidding)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_roas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target ROAS (if using Target ROAS bidding)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='geotemplate',
            name='default_match_type',
            field=models.CharField(choices=[('exact', 'Exact'), ('phrase', 'Phrase'), ('broad', 'Broad')], default='phrase', help_text='Standard match type for alle keywords', max_length=10),
        ),
        migrations.AddField(
            model_name='geotemplate',
            name='description_2_template',
            field=models.CharField(default='Erfaren {SERVICE} med 5/5 stjerner. Vi dækker {BYNAVN} og omegn.', help_text='Description 2 - max 90 karakterer', max_length=90),
        ),
        migrations.AddField(
            model_name='geotemplate',
            name='headline_3_template',
            field=models.CharField(default='Ring i dag - Gratis tilbud', help_text='Headline 3 - max 30 karakterer', max_length=30),
        ),
        migrations.AlterField(
            model_name='geotemplate',
            name='description_1_template',
            field=models.CharField(default='Professionel {SERVICE} i {BYNAVN} - Ring i dag for gratis tilbud!', help_text='Description 1 - max 90 karakterer', max_length=90),
        ),
        migrations.AlterField(
            model_name='geotemplate',
            name='headline_1_template',
            field=models.CharField(default='{SERVICE} {BYNAVN}', help_text='Headline 1 - max 30 karakterer', max_length=30),
        ),
        migrations.AlterField(
            model_name='geotemplate',
            name='headline_2_template',
            field=models.CharField(default='5/5 Stjerner Trustpilot', help_text='Headline 2 - max 30 karakterer', max_length=30),
        ),
    ]
