# Generated by Django 5.2.7 on 2025-11-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaign_ad_rotation_campaign_bidding_strategy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geotemplate',
            name='description_3_template',
            field=models.CharField(blank=True, help_text='Description 3 - max 90 karakterer', max_length=90),
        ),
        migrations.AddField(
            model_name='geotemplate',
            name='description_4_template',
            field=models.CharField(blank=True, help_text='Description 4 - max 90 karakterer', max_length=90),
        ),
        migrations.AddField(
            model_name='geotemplate',
            name='headline_10_template',
            field=models.CharField(blank=True, help_text='Headline 10 - max 30 karakterer', max_length=30),
        ),
        migrations.AddField(
            model_name='geotemplate',
            name='headline_11_template',
            field=models.CharField(blank=True, help_text='Headline 11 - max 30 karakterer', max_length=30),
        ),
        migrations.AddField(
            model_name='geotemplate',
            name='headline_12_template',
            field=models.CharField(blank=True, help_text='Headline 12 - max 30 karakterer', max_length=30),
        ),
        migrations.AddField(
            model_name='geotemplate',
            name='headline_13_template',
            field=models.CharField(blank=True, help_text='Headline 13 - max 30 karakterer', max_length=30),
        ),
        migrations.AddField(
            model_name='geotemplate',
            name='headline_14_template',
            field=models.CharField(blank=True, help_text='Headline 14 - max 30 karakterer', max_length=30),
        ),
        migrations.AddField(
            model_name='geotemplate',
            name='headline_15_template',
            field=models.CharField(blank=True, help_text='Headline 15 - max 30 karakterer', max_length=30),
        ),
        migrations.AddField(
            model_name='geotemplate',
            name='headline_4_template',
            field=models.CharField(blank=True, help_text='Headline 4 - max 30 karakterer', max_length=30),
        ),
        migrations.AddField(
            model_name='geotemplate',
            name='headline_5_template',
            field=models.CharField(blank=True, help_text='Headline 5 - max 30 karakterer', max_length=30),
        ),
        migrations.AddField(
            model_name='geotemplate',
            name='headline_6_template',
            field=models.CharField(blank=True, help_text='Headline 6 - max 30 karakterer', max_length=30),
        ),
        migrations.AddField(
            model_name='geotemplate',
            name='headline_7_template',
            field=models.CharField(blank=True, help_text='Headline 7 - max 30 karakterer', max_length=30),
        ),
        migrations.AddField(
            model_name='geotemplate',
            name='headline_8_template',
            field=models.CharField(blank=True, help_text='Headline 8 - max 30 karakterer', max_length=30),
        ),
        migrations.AddField(
            model_name='geotemplate',
            name='headline_9_template',
            field=models.CharField(blank=True, help_text='Headline 9 - max 30 karakterer', max_length=30),
        ),
    ]
