# Generated by Django 5.2.7 on 2025-11-13 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_geotemplate_description_3_template_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NegativeKeywordList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Navn på listen, f.eks. 'VVS Generel Negativ Liste'", max_length=100)),
                ('category', models.CharField(choices=[('general', 'Generel Negativ Liste'), ('job', 'Job/Karriere Negative'), ('diy', 'Gør Det Selv Negative'), ('competitor', 'Konkurrent Negative'), ('location', 'Lokation Negative'), ('service_specific', 'Service Specifik'), ('quality', 'Kvalitet/Pris Negative'), ('other', 'Andet')], default='general', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Beskrivelse af hvad denne liste indeholder')),
                ('is_active', models.BooleanField(default=True, help_text='Skal denne liste bruges automatisk i nye kampagner?')),
                ('auto_apply_to_industries', models.JSONField(blank=True, default=list, help_text='Industrier som denne liste automatisk skal anvendes på')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_uploaded_file', models.CharField(blank=True, max_length=255)),
                ('keywords_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Negative Keyword Liste',
                'verbose_name_plural': 'Negative Keyword Lister',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NegativeKeywordUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size_kb', models.IntegerField()),
                ('total_lines', models.IntegerField(default=0)),
                ('keywords_added', models.IntegerField(default=0)),
                ('keywords_skipped', models.IntegerField(default=0)),
                ('keywords_errors', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'Behandler'), ('completed', 'Færdig'), ('failed', 'Fejlet')], default='processing', max_length=20)),
                ('error_details', models.TextField(blank=True)),
                ('processing_notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('keyword_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.negativekeywordlist')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='NegativeKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_text', models.CharField(help_text='Negative keyword (uden minus tegn)', max_length=200)),
                ('match_type', models.CharField(choices=[('broad', 'Broad Match'), ('phrase', 'Phrase Match'), ('exact', 'Exact Match')], default='broad', max_length=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('source_file_line', models.IntegerField(blank=True, help_text='Linje nummer fra upload fil', null=True)),
                ('notes', models.CharField(blank=True, help_text='Noter om dette keyword', max_length=255)),
                ('keyword_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negative_keywords', to='campaigns.negativekeywordlist')),
            ],
            options={
                'ordering': ['keyword_text'],
                'unique_together': {('keyword_list', 'keyword_text', 'match_type')},
            },
        ),
        migrations.CreateModel(
            name='CampaignNegativeKeywordList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('included_in_last_export', models.BooleanField(default=False)),
                ('last_exported_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negative_lists', to='campaigns.campaign')),
                ('negative_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.negativekeywordlist')),
            ],
            options={
                'unique_together': {('campaign', 'negative_list')},
            },
        ),
    ]
