# Generated by Django 5.2.7 on 2025-11-16 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_negativekeywordlist_negativekeywordupload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='negativekeywordlist',
            name='industry',
            field=models.ForeignKey(blank=True, help_text='Primær branche denne liste er tilknyttet', null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.industry'),
        ),
        migrations.AlterField(
            model_name='negativekeywordlist',
            name='auto_apply_to_industries',
            field=models.JSONField(blank=True, default=list, help_text='Yderligere industrier som denne liste automatisk skal anvendes på'),
        ),
    ]
