# Generated by Django 5.2.7 on 2025-11-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_negativekeywordlist_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='negativekeywordlist',
            name='color',
            field=models.CharField(default='#8B5CF6', help_text='Hex farve kode for listen (f.eks. #8B5CF6)', max_length=7),
        ),
        migrations.AddField(
            model_name='negativekeywordlist',
            name='icon',
            field=models.CharField(default='📋', help_text='Emoji eller kort symbol for listen', max_length=10),
        ),
    ]
