# Generated by Django 5.2.7 on 2025-11-17 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_add_visual_settings_to_negative_keyword_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeographicRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Navn på området, f.eks. 'Nordsjælland Standard'", max_length=100)),
                ('category', models.CharField(choices=[('nordsjælland', 'Nordsjælland'), ('money', 'Money Byer'), ('trekant', 'Trekantsområdet'), ('storkøbenhavn', 'Storkøbenhavn'), ('jylland', 'Jylland'), ('fyn', 'Fyn'), ('bornholm', 'Bornholm'), ('custom', 'Brugerdefineret')], default='custom', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Beskrivelse af hvilke byer denne region indeholder')),
                ('icon', models.CharField(default='🗺️', help_text='Emoji eller kort symbol for regionen', max_length=10)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex farve kode for regionen (f.eks. #3B82F6)', max_length=7)),
                ('is_active', models.BooleanField(default=True, help_text='Skal denne region bruges til kampagner?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cities_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('industry', models.ForeignKey(blank=True, help_text='Primær branche denne region er tilknyttet', null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.industry')),
            ],
            options={
                'verbose_name': 'Geografisk Region',
                'verbose_name_plural': 'Geografiske Regioner',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeographicRegionUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size_kb', models.IntegerField()),
                ('total_lines', models.IntegerField(default=0)),
                ('cities_added', models.IntegerField(default=0)),
                ('cities_skipped', models.IntegerField(default=0)),
                ('cities_errors', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'Behandler'), ('completed', 'Færdig'), ('failed', 'Fejlet')], default='processing', max_length=20)),
                ('error_details', models.TextField(blank=True)),
                ('processing_notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.geographicregion')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DanishCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(help_text='Officielt bynavn', max_length=200)),
                ('city_synonym', models.CharField(blank=True, help_text="Synonym eller kendt som (f.eks. 'Nørrebro' for 'København N')", max_length=200)),
                ('postal_code', models.CharField(help_text="Postnummer (f.eks. '2880')", max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Breddegrad (latitude) for Google Ads targeting', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Længdegrad (longitude) for Google Ads targeting', max_digits=10, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('source_file_line', models.IntegerField(blank=True, help_text='Linje nummer fra upload fil', null=True)),
                ('notes', models.CharField(blank=True, help_text='Noter om denne by', max_length=255)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='campaigns.geographicregion')),
            ],
            options={
                'ordering': ['city_name'],
                'unique_together': {('region', 'city_name', 'postal_code')},
            },
        ),
    ]
