# Generated by Django 5.2.7 on 2025-11-18 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_geographicregion_geographicregionupload_danishcity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geographicregion',
            name='industry',
        ),
    ]
