# Generated by Django 5.2.7 on 2025-11-19 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_remove_industry_from_geographic_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='color',
            field=models.CharField(default='#3B82F6', help_text='Hex farve kode for branchen', max_length=7),
        ),
        migrations.AddField(
            model_name='industry',
            name='icon',
            field=models.CharField(default='🏢', help_text='Emoji icon for branchen', max_length=10),
        ),
        migrations.AddField(
            model_name='industry',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='industry',
            name='synonyms',
            field=models.JSONField(blank=True, default=list, help_text="Synonymer for branchen, f.eks. ['Kloakfirma', 'Kloakmand'] for 'Kloakmester'"),
        ),
        migrations.CreateModel(
            name='IndustryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Service navn, f.eks. 'Kloakrensning'", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Beskrivelse af servicen')),
                ('icon', models.CharField(default='⚙️', help_text='Emoji icon for servicen', max_length=10)),
                ('color', models.CharField(default='#8B5CF6', help_text='Hex farve kode for servicen', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_services', to='campaigns.industry')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'unique_together': {('industry', 'name')},
            },
        ),
        migrations.CreateModel(
            name='IndustryHeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline_text', models.CharField(help_text="Headline text med placeholders, f.eks. 'Professionel {SERVICE}'", max_length=30)),
                ('description', models.TextField(blank=True, help_text='Beskrivelse af hvornår denne headline bruges')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=1, help_text='Prioritetsrækkefølge (1 = højest)')),
                ('uses_service_placeholder', models.BooleanField(default=False, help_text='Bruger {SERVICE} placeholder')),
                ('uses_city_placeholder', models.BooleanField(default=False, help_text='Bruger {CITY} placeholder')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_headlines', to='campaigns.industry')),
            ],
            options={
                'ordering': ['priority', 'headline_text'],
                'unique_together': {('industry', 'headline_text')},
            },
        ),
        migrations.CreateModel(
            name='ServiceKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_text', models.CharField(help_text="Keyword text, f.eks. 'kloakrensning'", max_length=200)),
                ('match_type', models.CharField(choices=[('broad', 'Broad Match'), ('phrase', 'Phrase Match'), ('exact', 'Exact Match')], default='phrase', max_length=10)),
                ('is_primary', models.BooleanField(default=False, help_text='Er dette et primært keyword for servicen?')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('source_file_line', models.IntegerField(blank=True, help_text='Linje nummer fra upload fil', null=True)),
                ('notes', models.CharField(blank=True, help_text='Noter om dette keyword', max_length=255)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_keywords', to='campaigns.industryservice')),
            ],
            options={
                'ordering': ['-is_primary', 'keyword_text'],
                'unique_together': {('service', 'keyword_text', 'match_type')},
            },
        ),
    ]
