# Generated by Django 5.2.7 on 2025-11-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_industry_color_industry_icon_industry_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='default_negative_keyword_lists',
            field=models.ManyToManyField(blank=True, help_text='Standard negative søgeordslister for denne branche (kampagne-niveau)', related_name='default_for_industries', to='campaigns.negativekeywordlist'),
        ),
        migrations.AddField(
            model_name='industryservice',
            name='service_negative_keyword_lists',
            field=models.ManyToManyField(blank=True, help_text='Service-specifikke negative søgeordslister (annoncegruppe-niveau)', related_name='used_by_services', to='campaigns.negativekeywordlist'),
        ),
    ]
