# Generated by Django 5.2.7 on 2025-11-20 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0013_add_negative_keyword_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Navn på template, f.eks. 'Håndværker Standard', 'Service med Priser'", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Beskrivelse af hvornår denne template skal bruges')),
                ('headline_1_pattern', models.CharField(help_text="Template for headline 1, f.eks. '{PRIMARY_KEYWORD} fra kun {PRICE},-'", max_length=30)),
                ('headline_2_pattern', models.CharField(help_text="Template for headline 2, f.eks. '{USP_TRUST}' eller '{USP_SPEED}'", max_length=30)),
                ('headline_3_pattern', models.CharField(help_text="Template for headline 3, f.eks. '{USP_CTA}'", max_length=30)),
                ('description_1_pattern', models.CharField(help_text="Template for description 1, f.eks. 'Professionel {SERVICE} af erfarne fagfolk. {USP_TRUST}.'", max_length=90)),
                ('description_2_pattern', models.CharField(help_text="Template for description 2, f.eks. '{USP_SPEED}. {USP_CTA}.'", max_length=90)),
                ('final_url_pattern', models.CharField(default='{BASE_URL}', help_text="URL template, f.eks. '{BASE_URL}/{SERVICE_SLUG}' eller '{BASE_URL}/{CITY_SLUG}/{SERVICE_SLUG}'", max_length=200)),
                ('prioritize_trust_usps', models.BooleanField(default=True, help_text='Prioritér troværdigheds-USPs (Trustpilot, erfaring, etc.)')),
                ('prioritize_speed_usps', models.BooleanField(default=True, help_text='Prioritér hastigheds-USPs (samme dag, hurtig service, etc.)')),
                ('prioritize_price_usps', models.BooleanField(default=False, help_text='Prioritér pris-USPs (konkurrencedygtige priser, etc.)')),
                ('require_cta_usp', models.BooleanField(default=True, help_text='Kræv mindst én Call-to-Action USP')),
                ('is_default', models.BooleanField(default=False, help_text='Er dette default template for denne industry?')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('industry', models.ForeignKey(help_text='Branche denne template er designet til', on_delete=django.db.models.deletion.CASCADE, to='campaigns.industry')),
            ],
            options={
                'verbose_name': 'Ad Template',
                'verbose_name_plural': 'Ad Templates',
                'ordering': ['industry__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Navn på strategien, f.eks. 'Standard Håndværker', 'Akut Service'", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Beskrivelse af hvornår denne strategi skal bruges')),
                ('bidding_strategy', models.CharField(choices=[('enhanced_cpc', 'Enhanced CPC'), ('target_cpa', 'Target CPA'), ('maximize_clicks', 'Maximize Clicks'), ('manual_cpc', 'Manual CPC'), ('target_roas', 'Target ROAS')], default='enhanced_cpc', help_text='Google Ads bidding strategy', max_length=20)),
                ('default_daily_budget', models.DecimalField(decimal_places=2, help_text='Foreslået dagligt budget i DKK', max_digits=10)),
                ('default_cpc', models.DecimalField(blank=True, decimal_places=2, help_text='Standard CPC bid (hvis manual CPC eller enhanced CPC)', max_digits=8, null=True)),
                ('target_cpa', models.DecimalField(blank=True, decimal_places=2, help_text='Target CPA (hvis Target CPA strategi)', max_digits=8, null=True)),
                ('target_roas', models.DecimalField(blank=True, decimal_places=2, help_text='Target ROAS (hvis Target ROAS strategi)', max_digits=5, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Er dette en default strategi for nye kampagner?')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('industries', models.ManyToManyField(blank=True, help_text='Industrier denne strategi anbefales til', to='campaigns.industry')),
            ],
            options={
                'verbose_name': 'Budget Strategy',
                'verbose_name_plural': 'Budget Strategies',
                'ordering': ['name'],
            },
        ),
    ]
