# Generated by Django 5.2.7 on 2025-11-25 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0014_add_budget_and_ad_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSEOKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_text', models.CharField(help_text="SEO keyword text, f.eks. 'kloakrensning pris'", max_length=200)),
                ('search_volume', models.IntegerField(blank=True, help_text='Månedlig søgevolume (fra keyword tools)', null=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', help_text='SEO sværhedsgrad', max_length=10)),
                ('is_primary', models.BooleanField(default=False, help_text='Er dette et primært SEO keyword for servicen?')),
                ('target_url', models.URLField(blank=True, help_text='Target URL for dette keyword (valgfrit)')),
                ('current_ranking', models.IntegerField(blank=True, help_text='Nuværende Google ranking position', null=True)),
                ('notes', models.TextField(blank=True, help_text='SEO noter og strategi for dette keyword')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_keywords', to='campaigns.industryservice')),
            ],
            options={
                'ordering': ['-is_primary', 'search_volume', 'keyword_text'],
                'unique_together': {('service', 'keyword_text')},
            },
        ),
    ]
