# Generated by Django 5.2.7 on 2025-11-25 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0015_serviceseokeyword'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceNegativeKeywordList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('negative_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_connections', to='campaigns.negativekeywordlist')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negative_keyword_connections', to='campaigns.industryservice')),
            ],
            options={
                'verbose_name': 'Service Negative Keyword Connection',
                'verbose_name_plural': 'Service Negative Keyword Connections',
                'ordering': ['-connected_at'],
                'unique_together': {('service', 'negative_list')},
            },
        ),
    ]
