# Generated by Django 5.2.7 on 2025-11-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0016_servicenegativekeywordlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceseokeyword',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='serviceseokeyword',
            name='keyword_type',
            field=models.CharField(choices=[('money', 'Money Keyword'), ('price', 'Pris Keyword'), ('info', 'Informations Keyword'), ('lsi', 'LSI Keyword')], default='money', help_text='Type af SEO keyword', max_length=10),
        ),
    ]
