# Generated by Django 5.2.7 on 2025-11-26 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0017_remove_serviceseokeyword_difficulty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_text', models.CharField(help_text="Google Ads keyword text på branche-niveau, f.eks. 'kloakmester'", max_length=200)),
                ('match_type', models.CharField(choices=[('broad', 'Broad Match'), ('phrase', 'Phrase Match'), ('exact', 'Exact Match')], default='phrase', max_length=10)),
                ('is_primary', models.BooleanField(default=False, help_text='Er dette et primært keyword for branchen?')),
                ('inherited_by_services', models.BooleanField(default=True, help_text='Skal dette keyword automatisk nedarves til nye services?')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, help_text='Noter om dette branche keyword', max_length=255)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_keywords', to='campaigns.industry')),
            ],
            options={
                'ordering': ['-is_primary', 'keyword_text'],
                'unique_together': {('industry', 'keyword_text', 'match_type')},
            },
        ),
        migrations.CreateModel(
            name='IndustrySEOKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_text', models.CharField(help_text="SEO keyword text på branche-niveau, f.eks. 'kloakmester pris'", max_length=200)),
                ('search_volume', models.IntegerField(blank=True, help_text='Månedlig søgevolume (fra keyword tools)', null=True)),
                ('keyword_type', models.CharField(choices=[('money', 'Money Keyword'), ('price', 'Pris Keyword'), ('info', 'Informations Keyword'), ('lsi', 'LSI Keyword')], default='money', help_text='Type af SEO keyword på branche-niveau', max_length=10)),
                ('is_primary', models.BooleanField(default=False, help_text='Er dette et primært SEO keyword for branchen?')),
                ('inherited_by_services', models.BooleanField(default=True, help_text='Skal dette keyword automatisk nedarves til nye services?')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='SEO noter og strategi for dette branche keyword')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_seo_keywords', to='campaigns.industry')),
            ],
            options={
                'ordering': ['-is_primary', 'search_volume', 'keyword_text'],
                'unique_together': {('industry', 'keyword_text')},
            },
        ),
    ]
