# Generated by Django 5.2.7 on 2025-11-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0018_add_industry_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='industryservice',
            name='service_type',
            field=models.CharField(choices=[('service', 'Service'), ('industry_keywords', 'Branche Keywords'), ('synonym_keywords', 'Synonym Keywords')], default='service', help_text='Type af service - bruges til at skelne mellem services, branche keywords og synonym keywords', max_length=20),
        ),
    ]
