# Generated by Django 5.2.7 on 2025-11-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0019_industryservice_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industryservice',
            name='icon',
        ),
    ]
