# Generated by Django 5.2.7 on 2025-12-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0020_remove_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='requires_authorization',
            field=models.BooleanField(default=False, help_text='Angiver om branchen kan kræve autorisation (f.eks. elektriker, VVS)'),
        ),
    ]
