# Generated by Django 5.2.7 on 2025-12-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0021_add_requires_authorization_to_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='industry_authorizations',
            field=models.JSONField(blank=True, default=dict, help_text='Dict med branche_id -> boolean for autorisations-status'),
        ),
    ]
