# Generated by Django 5.2.7 on 2025-12-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0022_add_industry_authorizations_to_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='4-cifret postnummer (fx 2700)', max_length=4, unique=True)),
                ('dawa_name', models.CharField(help_text='Officielt navn fra DAWA (fx Brønshøj)', max_length=100)),
                ('display_name', models.CharField(blank=True, help_text='Custom visningsnavn (fx Nørrebro i stedet for København N)', max_length=100)),
                ('additional_names', models.TextField(blank=True, help_text='Kommaseparerede ekstra bynavne (fx Husum, Bellahøj)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Postnummer',
                'verbose_name_plural': 'Postnumre',
                'ordering': ['code'],
            },
        ),
    ]
