# Generated by Django 5.2.7 on 2026-01-07 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0023_add_postalcode_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaMarkupTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Navn på template, f.eks. 'VVS Product Schema'", max_length=100)),
                ('schema_type', models.CharField(choices=[('Product', 'Product'), ('LocalBusiness', 'Local Business'), ('Service', 'Service'), ('Organization', 'Organization'), ('AggregateRating', 'Aggregate Rating')], help_text='Type af schema markup', max_length=50)),
                ('template_json', models.TextField(help_text='JSON template med placeholders som {SERVICE_NAME}, {RATING}, {REVIEW_COUNT}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.ForeignKey(blank=True, help_text='Hvis sat, bruges denne template kun for denne branche', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schema_templates', to='campaigns.industry')),
            ],
            options={
                'verbose_name': 'Schema Markup Template',
                'verbose_name_plural': 'Schema Markup Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceMetaExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(help_text='Eksempel på god meta titel (50-60 tegn anbefales)', max_length=100)),
                ('meta_description', models.TextField(help_text='Eksempel på god meta beskrivelse (150-160 tegn anbefales)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Sorteringsrækkefølge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(help_text='Den service dette eksempel tilhører', on_delete=django.db.models.deletion.CASCADE, related_name='meta_examples', to='campaigns.industryservice')),
            ],
            options={
                'verbose_name': 'Meta Tag Eksempel',
                'verbose_name_plural': 'Meta Tag Eksempler',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
