# Generated by Django 5.2.7 on 2026-01-16 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0027_add_campaign_builder_fields_to_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_path', models.CharField(help_text='URL path, e.g. /elektriker-kobenhavn/', max_length=500)),
                ('full_url', models.URLField(blank=True)),
                ('created_by_us', models.BooleanField(default=False, help_text='Oprettet/exporteret af os')),
                ('found_in_sitemap', models.BooleanField(default=False, help_text='Fundet ved sitemap crawl')),
                ('page_type', models.CharField(choices=[('byside', 'Byside'), ('service', 'Serviceside'), ('blog', 'Blogindlæg'), ('other', 'Andre sider')], default='service', max_length=20)),
                ('last_modified_header', models.DateTimeField(blank=True, help_text='Last-Modified header fra HTTP response', null=True)),
                ('etag', models.CharField(blank=True, max_length=500)),
                ('content_hash', models.CharField(blank=True, help_text='SHA256 hash af side-indhold', max_length=64)),
                ('first_discovered_at', models.DateTimeField(auto_now_add=True)),
                ('last_crawled_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('exported_at', models.DateTimeField(blank=True, help_text='Hvornår siden blev exporteret fra Campaign Builder', null=True)),
                ('meta_title', models.CharField(blank=True, max_length=500)),
                ('meta_description', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_pages', to='campaigns.client')),
            ],
            options={
                'verbose_name': 'Tracked Page',
                'verbose_name_plural': 'Tracked Pages',
                'ordering': ['-last_crawled_at'],
                'unique_together': {('client', 'url_path')},
            },
        ),
    ]
