# Generated by Django 5.2.7 on 2025-11-04 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='USPCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'USP Categories',
            },
        ),
        migrations.CreateModel(
            name='IndustryUSPPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(help_text='Regex pattern til at finde USPs', max_length=200)),
                ('description', models.TextField()),
                ('weight', models.FloatField(default=1.0)),
                ('examples', models.TextField(help_text='Eksempler på tekst der matcher dette pattern')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.industry')),
            ],
            options={
                'verbose_name_plural': 'Industry USP Patterns',
            },
        ),
        migrations.CreateModel(
            name='USPTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('urgency_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('keywords', models.TextField(help_text='Komma-separerede søgeord der trigger denne USP')),
                ('effectiveness_score', models.FloatField(default=0.5, help_text='Score mellem 0 og 1')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usps.uspcategory')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.industry')),
            ],
            options={
                'verbose_name_plural': 'USP Templates',
            },
        ),
        migrations.CreateModel(
            name='ClientUSP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_text', models.CharField(max_length=200)),
                ('is_discovered', models.BooleanField(default=False, help_text='Fundet via website crawling')),
                ('is_selected', models.BooleanField(default=True)),
                ('source_url', models.URLField(blank=True, help_text='URL hvor USP blev fundet')),
                ('confidence_score', models.FloatField(default=0.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.client')),
                ('usp_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usps.usptemplate')),
            ],
            options={
                'verbose_name_plural': 'Client USPs',
            },
        ),
    ]
