# Generated by Django 5.2.7 on 2025-11-13 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_negativekeywordlist_negativekeywordupload_and_more'),
        ('usps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='USPMainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="F.eks. 'Hurtigt tilbud/hurtig service'", max_length=100)),
                ('description', models.TextField(help_text='Forklaring af kategoriens formål')),
                ('icon', models.CharField(default='⚡', help_text='Emoji ikon til UI', max_length=10)),
                ('color', models.CharField(default='#8B5CF6', help_text='Hex farve til UI', max_length=7)),
                ('sort_order', models.IntegerField(default=1, help_text='Sorteringsrækkefølge')),
                ('is_recommended_per_campaign', models.BooleanField(default=True, help_text='Om kategorien anbefales i hver kampagne')),
                ('max_selections', models.IntegerField(default=1, help_text='Maks antal USPs fra denne kategori per kampagne')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'USP Main Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='industryusppattern',
            options={'verbose_name_plural': 'Industry USP Patterns (Legacy)'},
        ),
        migrations.AlterModelOptions(
            name='uspcategory',
            options={'verbose_name_plural': 'USP Categories (Legacy)'},
        ),
        migrations.AlterModelOptions(
            name='usptemplate',
            options={'ordering': ['main_category__sort_order', 'priority_rank', 'text'], 'verbose_name_plural': 'USP Templates'},
        ),
        migrations.RemoveField(
            model_name='usptemplate',
            name='industry',
        ),
        migrations.AddField(
            model_name='usptemplate',
            name='example_headlines',
            field=models.JSONField(default=list, help_text='Array med eksempel headlines baseret på denne USP'),
        ),
        migrations.AddField(
            model_name='usptemplate',
            name='explanation',
            field=models.TextField(blank=True, help_text='Forklaring af hvornår denne USP skal bruges'),
        ),
        migrations.AddField(
            model_name='usptemplate',
            name='ideal_for_industries',
            field=models.ManyToManyField(blank=True, help_text='Industrier denne USP passer bedst til', to='campaigns.industry'),
        ),
        migrations.AddField(
            model_name='usptemplate',
            name='placeholders_used',
            field=models.JSONField(default=list, help_text="Array med placeholders brugt, f.eks. ['{SERVICE}', '{BYNAVN}']"),
        ),
        migrations.AddField(
            model_name='usptemplate',
            name='priority_rank',
            field=models.IntegerField(default=1, help_text='1 = højest prioritet (øverste i listen)'),
        ),
        migrations.AddField(
            model_name='usptemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usptemplate',
            name='use_cases',
            field=models.JSONField(default=list, help_text="Array med use cases, f.eks. ['let_at_udregne', 'telefon_vurdering']"),
        ),
        migrations.AlterField(
            model_name='usptemplate',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Legacy kategori - brug main_category i stedet', null=True, on_delete=django.db.models.deletion.CASCADE, to='usps.uspcategory'),
        ),
        migrations.AlterField(
            model_name='usptemplate',
            name='effectiveness_score',
            field=models.FloatField(default=0.5, help_text='Performance score mellem 0 og 1 (opdateres automatisk)'),
        ),
        migrations.AlterField(
            model_name='usptemplate',
            name='keywords',
            field=models.TextField(blank=True, help_text='Komma-separerede søgeord'),
        ),
        migrations.AlterField(
            model_name='usptemplate',
            name='text',
            field=models.CharField(help_text='USP teksten', max_length=200),
        ),
        migrations.CreateModel(
            name='USPCategoryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="F.eks. 'Håndværker Standard 5-Pack'", max_length=100)),
                ('description', models.TextField(help_text='Beskrivelse af template')),
                ('category_data', models.JSONField(help_text='Array af kategori objekter')),
                ('auto_populate_usps', models.BooleanField(default=True, help_text='Auto-populer med standard USPs')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_industries', models.ManyToManyField(blank=True, to='campaigns.industry')),
            ],
            options={
                'verbose_name_plural': 'USP Category Templates',
            },
        ),
        migrations.AddField(
            model_name='usptemplate',
            name='main_category',
            field=models.ForeignKey(blank=True, help_text='Hovedkategori (ny struktur)', null=True, on_delete=django.db.models.deletion.CASCADE, to='usps.uspmaincategory'),
        ),
        migrations.CreateModel(
            name='USPSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="F.eks. 'Murer Kampagne - Frederiksberg'", max_length=100)),
                ('service_name', models.CharField(blank=True, help_text="F.eks. 'Murer', 'VVS'", max_length=100)),
                ('target_areas', models.JSONField(default=list, help_text='Array med målrettede områder')),
                ('is_template', models.BooleanField(default=False, help_text='Om dette sæt kan bruges som template for andre')),
                ('effectiveness_score', models.FloatField(default=0.0, help_text='Samlet effectiveness score for dette USP-sæt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, help_text='Tilknyttet kampagne (valgfri)', null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.industry')),
                ('selected_usps', models.ManyToManyField(help_text='Valgte USPs til denne kampagne', to='usps.usptemplate')),
            ],
            options={
                'verbose_name_plural': 'USP Sets',
            },
        ),
    ]
