# Generated by Django 5.2.7 on 2025-11-13 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_negativekeywordlist_negativekeywordupload_and_more'),
        ('usps', '0002_uspmaincategory_alter_industryusppattern_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientusp',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='Tilknyttet kampagne', null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='clientusp',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='True hvis helt ny USP (ikke baseret på template)'),
        ),
        migrations.AddField(
            model_name='clientusp',
            name='is_modified',
            field=models.BooleanField(default=False, help_text='True hvis custom_text er ændret fra original template'),
        ),
        migrations.AddField(
            model_name='clientusp',
            name='original_text',
            field=models.CharField(blank=True, help_text='Original template tekst (for tracking changes)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientusp',
            name='custom_text',
            field=models.CharField(help_text='Final tekst brugt for denne kampagne', max_length=200),
        ),
        migrations.AlterField(
            model_name='clientusp',
            name='usp_template',
            field=models.ForeignKey(blank=True, help_text='Original template (null for custom USPs)', null=True, on_delete=django.db.models.deletion.CASCADE, to='usps.usptemplate'),
        ),
    ]
