# Generated by Django 5.2.7 on 2025-11-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usps', '0003_add_flexible_usp_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='usptemplate',
            name='best_for_description',
            field=models.TextField(blank=True, help_text='Bedste version til descriptions (kan være længere)'),
        ),
        migrations.AddField(
            model_name='usptemplate',
            name='best_for_headline',
            field=models.CharField(blank=True, help_text='Primær anbefalet headline version (max 30 karakterer)', max_length=30),
        ),
        migrations.AddField(
            model_name='usptemplate',
            name='short_headlines',
            field=models.JSONField(default=list, help_text="Array med korte headline versioner (max 30 chars), f.eks. ['Ring nu - få pris', 'Pris i telefonen']"),
        ),
    ]
