# Generated by Django 5.2.7 on 2025-11-14 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usps', '0004_add_headline_variations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usptemplate',
            name='best_for_description',
        ),
        migrations.RemoveField(
            model_name='usptemplate',
            name='best_for_headline',
        ),
    ]
