# Generated by Django 5.2.7 on 2025-11-14 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usps', '0005_remove_best_for_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usptemplate',
            name='short_headlines',
        ),
        migrations.RemoveField(
            model_name='usptemplate',
            name='use_cases',
        ),
    ]
