# Generated by Django 5.2.7 on 2025-11-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usps', '0006_remove_usptemplate_short_headlines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usptemplate',
            name='is_cta',
            field=models.BooleanField(default=False, help_text="Er denne USP en Call-to-Action? (f.eks. 'Få en pris på 2 min', 'Ring nu og få tilbud')"),
        ),
    ]
